jyo = "Hello TACT"
print("Initial String:")
print(jyo)
jyo = "Welcome to TACT"
print("\nUpdated string:")
print(jyo)
print("\nCharacters from 3-5:")
print ("jyo[2:5]:", jyo[2:5])
print("\n Characters between "+"3rd and 2nd last character")
print ("jyo[3:-2]:",jyo[3:-2])
print("\nPrinting string 4 times")
print (jyo*4)
print("\nAdding element to the string:")
print(jyo +"TEAM")
print("\nFinding the index of the element: ")
"Hello tact TEAM".index("E")
